export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'


export const POST_USERS_REQUEST = 'POST_USERS_REQUEST'
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS'
export const POST_USERS_FAILURE = 'POST_USERS_FAILURE'


export const EDIT_USERS_REQUEST = 'EDIT_USERS_REQUEST'
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS'
export const EDIT_USERS_FAILURE = 'EDIT_USERS_FAILURE'

export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST'
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS'
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE'